#print(" enter the two numbers")
num1= int(input("enter num1:"))
num2 =int(input("enter  num2:"))
num3 = int(input("enter  num3:"))
sum=print(num1+num2)
substract=print(num1-num2)
multiply=print(num1*num2)
remainder=print(num1%num2)
power=print(num1**num2)
divide=print(num1/num2)
sum3 = print(sum+num2)
substract3=print(substract-num2)
multiply3=print(multiply*num2)
remainder3=print(remainder%num2)
power3=print(power**num2)
divide3=print(divide/num2)
print(sum3)
print(substract3)
print(multiply3)
print(remainder3)
print(power3)
print(divide3)
