#print(" enter the two numbers")
num1= int(input("enter num1:"))
num2 =int(input("enter  num2:"))
sum=print(num1+num2)
substract=print(num1-num2)
multiply=print(num1*num2)
remainder=print(num1%num2)
power=print(num1**num2)
divide=print(num1/num2)
print(sum)
print(substract)
print(multiply)
print(remainder)
print(power)
print(divide)